export { default as Home } from './home/Home'
export { default as Login } from './login/Login'
export { default as Register } from './register/Register'
export { default as Admin} from './admin/Admin'
export { default as Missing} from './Missing'
export { default as Profile} from './profile/Profile'
export { default as Explore} from './explore/Explore'
export { default as Messages} from './messages/Messages'
export { default as PostDetail} from './PostDetail/PostDetail'
export { default as SavedPost} from './savedPost/SavedPost'
export { default as Settings}from './settings/Settings'